/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendorServicesRouteImport } from './routes/vendor.services'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorPayoutsRouteImport } from './routes/vendor.payouts'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SellerAuthRouteImport } from './routes/seller.auth'
import { Route as RShortCodeRouteImport } from './routes/r.$shortCode'
import { Route as PPartnerRouteImport } from './routes/p.$partner'
import { Route as DeliveryProfileRouteImport } from './routes/delivery.profile'
import { Route as DeliveryOnboardingRouteImport } from './routes/delivery.onboarding'
import { Route as DeliveryEarningsRouteImport } from './routes/delivery.earnings'
import { Route as DeliveryAuthRouteImport } from './routes/delivery.auth'
import { Route as DeliveryAssignmentsRouteImport } from './routes/delivery.assignments'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminOndcRouteImport } from './routes/admin.ondc'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as OrdersIdTrackRouteImport } from './routes/orders.$id.track'
import { Route as ApiPublicPostbacksNetworkRouteImport } from './routes/api/public/postbacks.$network'
import { Route as ApiPublicOndcSplatRouteImport } from './routes/api/public/ondc.$'

const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeliveryRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendorServicesRoute = VendorServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorPayoutsRoute = VendorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAuthRoute = SellerAuthRouteImport.update({
  id: '/seller/auth',
  path: '/seller/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RShortCodeRoute = RShortCodeRouteImport.update({
  id: '/r/$shortCode',
  path: '/r/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PPartnerRoute = PPartnerRouteImport.update({
  id: '/p/$partner',
  path: '/p/$partner',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryProfileRoute = DeliveryProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryOnboardingRoute = DeliveryOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryEarningsRoute = DeliveryEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryAuthRoute = DeliveryAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DeliveryRoute,
} as any)
const DeliveryAssignmentsRoute = DeliveryAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DeliveryRoute,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOndcRoute = AdminOndcRouteImport.update({
  id: '/ondc',
  path: '/ondc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIdTrackRoute = OrdersIdTrackRouteImport.update({
  id: '/$id/track',
  path: '/$id/track',
  getParentRoute: () => OrdersRoute,
} as any)
const ApiPublicPostbacksNetworkRoute =
  ApiPublicPostbacksNetworkRouteImport.update({
    id: '/api/public/postbacks/$network',
    path: '/api/public/postbacks/$network',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOndcSplatRoute = ApiPublicOndcSplatRouteImport.update({
  id: '/api/public/ondc/$',
  path: '/api/public/ondc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/ondc': typeof AdminOndcRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$category': typeof CCategoryRoute
  '/delivery/assignments': typeof DeliveryAssignmentsRoute
  '/delivery/auth': typeof DeliveryAuthRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/onboarding': typeof DeliveryOnboardingRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/p/$partner': typeof PPartnerRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/seller/auth': typeof SellerAuthRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/services': typeof VendorServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/api/public/ondc/$': typeof ApiPublicOndcSplatRoute
  '/api/public/postbacks/$network': typeof ApiPublicPostbacksNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/ondc': typeof AdminOndcRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$category': typeof CCategoryRoute
  '/delivery/assignments': typeof DeliveryAssignmentsRoute
  '/delivery/auth': typeof DeliveryAuthRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/onboarding': typeof DeliveryOnboardingRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/p/$partner': typeof PPartnerRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/seller/auth': typeof SellerAuthRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/services': typeof VendorServicesRoute
  '/admin': typeof AdminIndexRoute
  '/delivery': typeof DeliveryIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/api/public/ondc/$': typeof ApiPublicOndcSplatRoute
  '/api/public/postbacks/$network': typeof ApiPublicPostbacksNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/delivery': typeof DeliveryRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/banners': typeof AdminBannersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/ondc': typeof AdminOndcRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/c/$category': typeof CCategoryRoute
  '/delivery/assignments': typeof DeliveryAssignmentsRoute
  '/delivery/auth': typeof DeliveryAuthRoute
  '/delivery/earnings': typeof DeliveryEarningsRoute
  '/delivery/onboarding': typeof DeliveryOnboardingRoute
  '/delivery/profile': typeof DeliveryProfileRoute
  '/p/$partner': typeof PPartnerRoute
  '/r/$shortCode': typeof RShortCodeRoute
  '/seller/auth': typeof SellerAuthRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/payouts': typeof VendorPayoutsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/services': typeof VendorServicesRoute
  '/admin/': typeof AdminIndexRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/api/public/ondc/$': typeof ApiPublicOndcSplatRoute
  '/api/public/postbacks/$network': typeof ApiPublicPostbacksNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/delivery'
    | '/orders'
    | '/rewards'
    | '/search'
    | '/vendor'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/links'
    | '/admin/ondc'
    | '/admin/partners'
    | '/admin/services'
    | '/admin/users'
    | '/admin/vendors'
    | '/c/$category'
    | '/delivery/assignments'
    | '/delivery/auth'
    | '/delivery/earnings'
    | '/delivery/onboarding'
    | '/delivery/profile'
    | '/p/$partner'
    | '/r/$shortCode'
    | '/seller/auth'
    | '/services/$slug'
    | '/vendor/orders'
    | '/vendor/payouts'
    | '/vendor/products'
    | '/vendor/services'
    | '/admin/'
    | '/delivery/'
    | '/vendor/'
    | '/orders/$id/track'
    | '/api/public/ondc/$'
    | '/api/public/postbacks/$network'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/categories'
    | '/orders'
    | '/rewards'
    | '/search'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/links'
    | '/admin/ondc'
    | '/admin/partners'
    | '/admin/services'
    | '/admin/users'
    | '/admin/vendors'
    | '/c/$category'
    | '/delivery/assignments'
    | '/delivery/auth'
    | '/delivery/earnings'
    | '/delivery/onboarding'
    | '/delivery/profile'
    | '/p/$partner'
    | '/r/$shortCode'
    | '/seller/auth'
    | '/services/$slug'
    | '/vendor/orders'
    | '/vendor/payouts'
    | '/vendor/products'
    | '/vendor/services'
    | '/admin'
    | '/delivery'
    | '/vendor'
    | '/orders/$id/track'
    | '/api/public/ondc/$'
    | '/api/public/postbacks/$network'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/delivery'
    | '/orders'
    | '/rewards'
    | '/search'
    | '/vendor'
    | '/admin/banners'
    | '/admin/delivery'
    | '/admin/links'
    | '/admin/ondc'
    | '/admin/partners'
    | '/admin/services'
    | '/admin/users'
    | '/admin/vendors'
    | '/c/$category'
    | '/delivery/assignments'
    | '/delivery/auth'
    | '/delivery/earnings'
    | '/delivery/onboarding'
    | '/delivery/profile'
    | '/p/$partner'
    | '/r/$shortCode'
    | '/seller/auth'
    | '/services/$slug'
    | '/vendor/orders'
    | '/vendor/payouts'
    | '/vendor/products'
    | '/vendor/services'
    | '/admin/'
    | '/delivery/'
    | '/vendor/'
    | '/orders/$id/track'
    | '/api/public/ondc/$'
    | '/api/public/postbacks/$network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  DeliveryRoute: typeof DeliveryRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  VendorRoute: typeof VendorRouteWithChildren
  CCategoryRoute: typeof CCategoryRoute
  PPartnerRoute: typeof PPartnerRoute
  RShortCodeRoute: typeof RShortCodeRoute
  SellerAuthRoute: typeof SellerAuthRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ApiPublicOndcSplatRoute: typeof ApiPublicOndcSplatRoute
  ApiPublicPostbacksNetworkRoute: typeof ApiPublicPostbacksNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendor/services': {
      id: '/vendor/services'
      path: '/services'
      fullPath: '/vendor/services'
      preLoaderRoute: typeof VendorServicesRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/payouts': {
      id: '/vendor/payouts'
      path: '/payouts'
      fullPath: '/vendor/payouts'
      preLoaderRoute: typeof VendorPayoutsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/auth': {
      id: '/seller/auth'
      path: '/seller/auth'
      fullPath: '/seller/auth'
      preLoaderRoute: typeof SellerAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shortCode': {
      id: '/r/$shortCode'
      path: '/r/$shortCode'
      fullPath: '/r/$shortCode'
      preLoaderRoute: typeof RShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$partner': {
      id: '/p/$partner'
      path: '/p/$partner'
      fullPath: '/p/$partner'
      preLoaderRoute: typeof PPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/profile': {
      id: '/delivery/profile'
      path: '/profile'
      fullPath: '/delivery/profile'
      preLoaderRoute: typeof DeliveryProfileRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/onboarding': {
      id: '/delivery/onboarding'
      path: '/onboarding'
      fullPath: '/delivery/onboarding'
      preLoaderRoute: typeof DeliveryOnboardingRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/earnings': {
      id: '/delivery/earnings'
      path: '/earnings'
      fullPath: '/delivery/earnings'
      preLoaderRoute: typeof DeliveryEarningsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/auth': {
      id: '/delivery/auth'
      path: '/auth'
      fullPath: '/delivery/auth'
      preLoaderRoute: typeof DeliveryAuthRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/delivery/assignments': {
      id: '/delivery/assignments'
      path: '/assignments'
      fullPath: '/delivery/assignments'
      preLoaderRoute: typeof DeliveryAssignmentsRouteImport
      parentRoute: typeof DeliveryRoute
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ondc': {
      id: '/admin/ondc'
      path: '/ondc'
      fullPath: '/admin/ondc'
      preLoaderRoute: typeof AdminOndcRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$id/track': {
      id: '/orders/$id/track'
      path: '/$id/track'
      fullPath: '/orders/$id/track'
      preLoaderRoute: typeof OrdersIdTrackRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/api/public/postbacks/$network': {
      id: '/api/public/postbacks/$network'
      path: '/api/public/postbacks/$network'
      fullPath: '/api/public/postbacks/$network'
      preLoaderRoute: typeof ApiPublicPostbacksNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ondc/$': {
      id: '/api/public/ondc/$'
      path: '/api/public/ondc/$'
      fullPath: '/api/public/ondc/$'
      preLoaderRoute: typeof ApiPublicOndcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminOndcRoute: typeof AdminOndcRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminOndcRoute: AdminOndcRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DeliveryRouteChildren {
  DeliveryAssignmentsRoute: typeof DeliveryAssignmentsRoute
  DeliveryAuthRoute: typeof DeliveryAuthRoute
  DeliveryEarningsRoute: typeof DeliveryEarningsRoute
  DeliveryOnboardingRoute: typeof DeliveryOnboardingRoute
  DeliveryProfileRoute: typeof DeliveryProfileRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
}

const DeliveryRouteChildren: DeliveryRouteChildren = {
  DeliveryAssignmentsRoute: DeliveryAssignmentsRoute,
  DeliveryAuthRoute: DeliveryAuthRoute,
  DeliveryEarningsRoute: DeliveryEarningsRoute,
  DeliveryOnboardingRoute: DeliveryOnboardingRoute,
  DeliveryProfileRoute: DeliveryProfileRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
}

const DeliveryRouteWithChildren = DeliveryRoute._addFileChildren(
  DeliveryRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdTrackRoute: typeof OrdersIdTrackRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdTrackRoute: OrdersIdTrackRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface VendorRouteChildren {
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorPayoutsRoute: typeof VendorPayoutsRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorServicesRoute: typeof VendorServicesRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorOrdersRoute: VendorOrdersRoute,
  VendorPayoutsRoute: VendorPayoutsRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorServicesRoute: VendorServicesRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  DeliveryRoute: DeliveryRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  VendorRoute: VendorRouteWithChildren,
  CCategoryRoute: CCategoryRoute,
  PPartnerRoute: PPartnerRoute,
  RShortCodeRoute: RShortCodeRoute,
  SellerAuthRoute: SellerAuthRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ApiPublicOndcSplatRoute: ApiPublicOndcSplatRoute,
  ApiPublicPostbacksNetworkRoute: ApiPublicPostbacksNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
